# Generated by Django 3.0.6 on 2020-06-07 15:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finstateapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0, verbose_name='Value')),
                ('units', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BLR', 'BLR')], default='BLR', max_length=3, verbose_name='Units')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Report calculation date')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Stare report calculation date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='End report calculation date')),
            ],
            bases=(models.Model, finstateapp.models.ReportInterface),
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Holding name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Factory name')),
                ('requisites', models.CharField(max_length=100, verbose_name='Factory requisites')),
                ('symbol', models.CharField(max_length=10, verbose_name='Factory requisites')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone number')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finstateapp.Holding')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Liabilities',
            fields=[
                ('index_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finstateapp.Index')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(default='', max_length=200, verbose_name='Description')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finstateapp.Factory')),
            ],
            bases=('finstateapp.index',),
        ),
        migrations.CreateModel(
            name='IncomeStatementReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finstateapp.Report')),
                ('revenue', models.FloatField(default=0, verbose_name='Revenue')),
                ('gross_profit', models.FloatField(default=0, verbose_name='Gross profit')),
                ('operating_income', models.FloatField(default=0, verbose_name='Operating income')),
                ('income_before_tax', models.FloatField(default=0, verbose_name='Income before tax')),
                ('net_income', models.FloatField(default=0, verbose_name='Net income')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finstateapp.Factory')),
            ],
            bases=('finstateapp.report',),
        ),
        migrations.CreateModel(
            name='DigitalIndex',
            fields=[
                ('index_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finstateapp.Index')),
                ('name', models.CharField(choices=[('Ivolume of sold', 'volume of sold(объем продаж)'), ('Iaverage check', 'average check(средний чек)'), ('Icost price', 'cost price(себестоимость)'), ('Iselling expenses', 'selling expenses(упаковка, доставка, аренда, зарплата)'), ('Iother operating expenses', 'other operating expenses'), ('Iother expenses', 'other expenses(проценты по кредитам, штрафы)'), ('Iother income', 'other income(проценты по вкладам, безвозмездное получение активов)'), ('Iincome tax', 'income tax'), ('Cnon-cash expenses', 'non-cash expenses'), ('Cnon-cash income', 'non-cash income'), ('Cstock acquisition', 'stock acquisition(приобретение запасов)'), ('Cadvances paid', 'advances paid(оплата услуг раньше срока)'), ('Cadvances received', 'advances received(получение за услуги до срока)')], max_length=100, verbose_name='Name')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finstateapp.Factory')),
            ],
            bases=('finstateapp.index',),
        ),
        migrations.CreateModel(
            name='CashFlowStatementReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finstateapp.Report')),
                ('operating_cash_flow', models.FloatField(default=0, verbose_name='Operating cash flow')),
                ('cash_from_operations', models.FloatField(default=0, verbose_name='Cash from operations')),
                ('cash_net_income', models.FloatField(default=0, verbose_name='Cash net income')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finstateapp.Factory')),
            ],
            bases=('finstateapp.report',),
        ),
        migrations.CreateModel(
            name='BalanceReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finstateapp.Report')),
                ('assets', models.FloatField(default=0, verbose_name='Assets cost')),
                ('liabilities', models.FloatField(default=0, verbose_name='Liabilities cost')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finstateapp.Factory')),
            ],
            bases=('finstateapp.report',),
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('index_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finstateapp.Index')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(default='', max_length=200, verbose_name='Description')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finstateapp.Factory')),
            ],
            bases=('finstateapp.index',),
        ),
    ]
