# Generated by Django 3.0.6 on 2020-06-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finstateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='is_reported_already',
            field=models.BooleanField(default=False),
        ),
    ]
